import dns from "node:dns";
dns.setServers(['8.8.8.8', '8.8.4.4'])

import { Nunito } from "next/font/google";
import "./globals.css";
import { Bounce, Slide, ToastContainer } from "react-toastify";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme="dark"
      suppressHydrationWarning={true}
      lang="en"
      className={`${nunito.variable} dark`}
      style={{ fontFamily: "var(--font-nunito), sans-serif" }}
    >
      <body className="bg-background text-foreground w-full">
        {children}
        <ToastContainer
          position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop
          closeOnClick={true}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover={false}
          theme="colored"
          transition={Slide}
        />
      </body>
    </html>
  );
}